Repository wanted-pre-onboarding-fe-team-4/week1-todo-app, pull requests merged in 2023-02, with the labels that each got.

#10 [#8, #9] vscode setting.json 저장시 자동정렬 옵션 추가, 절대경로 tsconfig baseUrl 경로 수정
  .vscode/settings.json
  tsconfig.json
Labels: bug, enhancement

#5 [#1] api query custom hook 개발
  src/api/index.ts
  src/hooks/index.tsx
  src/hooks/useQuery.tsx
  src/types/ErrorsType.ts
Labels: enhancement

#7 [#6] 로그인 상태 확인 custom hook 개발
  src/hooks/useLoggedIn.tsx
Labels: enhancement

#16 [#15] Push 전에 lint 수행하도록 Git Hook 설치
  .eslintrc
  .husky/pre-push
  package.json
  src/hooks/index.tsx
  yarn.lock
Labels: enhancement

#18 [#14] 레이아웃 구성
  src/components/Layouts/DefaultLayout.tsx
  src/components/Layouts/Header.tsx
  src/components/commons/routes/AppRouter.tsx
  src/components/commons/styles/colors.tsx
Labels: enhancement

#19 [#17] 공통버튼, 인풋 개발
  src/components/commons/buttons/CommonButton.tsx
  src/components/commons/inputs/CommonInput.tsx
Labels: enhancement

#24 [#23] axios 기본 설정 오류 해결
  src/api/index.ts
Labels: bug

#27 [#21] todo update, delete 함수 개발
  src/context/TodoContext.tsx
  src/pages/Todo.tsx
  src/types/ITodo.ts
Labels: enhancement

#35 [#33, #34, #36] todo 페이지 개발
  src/pages/Todo.tsx
  src/pages/Todo/index.tsx
  src/pages/Todo/style.tsx
  src/pages/Todo/todo.tsx
  src/pages/Todo/todoListItem.tsx
  yarn.lock
Labels: enhancement

#52 [#48] favicon && app name && app description
  public/favicon.ico
  public/favicon2.ico
  public/index.html
Labels: enhancement

#62 [#60] Todo checked checkbox cursor pointer
  src/pages/Todo/todoListItem.tsx
Labels: enhancement
